GET http://localhost:3001/api/lendings
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlkaWFkbWluIiwiaWQiOiI1YWNmOGEwZGEyM2VkMThhYTJhM2IxNTUiLCJpYXQiOjE1MjM1NTM4Mjh9.F0crlkt20JFuQymVQ5W0gPSY8vNdFPiojImnY59KddA
