POST http://localhost:3003/api/lendings
content-type: application/json

{
      "customer": "5ac91e3807ed9112067b86d5",
      "products": [
            {
                  "id": "5ac9c59fc88065241ff9e2db",
                  "amount": 4
            }
      ],
      "deadline": "2018-06-06"
}