POST http://localhost:3003/api/products
content-type: application/json

{
      "name": "Saappaat",
      "size": "41",
      "description": "mustat, nahkaa",
      "amount": 100,
      "amountInStorage": 100,
      "category": "jalkineet"
}